name: AutomatScript CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Ensure necessary directories exist
        run: mkdir -p bin/tmp

      - name: Fix permissions
        run: chmod -R 777 bin/

      - name: Create dummy logfile to prevent errors
        run: mkdir -p bin/tmp && touch bin/tmp/cppcode.cpp

      - name: Build Transpiler
        run: make

      - name: Run Tests
        run: |
          for test_file in tests/*.as; do
            echo "Running $test_file..."
            ./bin/transpile "$test_file" > output.txt
            diff output.txt "tests/expected/$(basename $test_file .as).txt"
          done
